# Generated by Django 5.1.1 on 2024-09-30 00:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='contato_pais',
            field=models.CharField(default='N/A', max_length=200, verbose_name='Contato dos Pais'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_entrada_programa',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada no Programa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01', verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_saida_programa',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Saída do Programa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='endereco',
            field=models.TextField(default='N/A', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='educador',
            name='turma_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educadores_responsaveis', to='cadastros.turma', verbose_name='Turma Responsável'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='detalhes_necessidade_especial',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Necessidade Especial'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='necessidade_especial',
            field=models.BooleanField(default=False, verbose_name='Necessidade Especial'),
        ),
    ]
