# Generated by Django 4.2.5 on 2024-10-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_aluno_contato_pais_aluno_data_entrada_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='horario',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
    ]
