# Generated by Django 5.1.4 on 2024-12-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_turma_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Aula')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('educador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='cadastros.educador')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cadastros.turma')),
            ],
        ),
    ]
